from django.urls import path
from .views import ( 
    AddPermissionsAPIView, 
    EtudiantsAPIView, 
    ProfesseursAPIView, 
    UsersAPIView, 
    RegisterAPIView, 
    CustomTokenObtainPairView,
    EnrollmentView,
    CourseView,
    ResultView,
    DepartmentView,
    ContentCourseView,
    DepartmentView,
    UserInfoView,
    SpecialityView,
    ActivityRepportView,
    EvaluationView,
    QuestionsView
)
from rest_framework_simplejwt.views import TokenRefreshView, TokenBlacklistView

urlpatterns = [
    path('user_info/', UserInfoView.as_view(), name='user_info'),
    path('register/', RegisterAPIView.as_view(), name='register'),
    path('login/', CustomTokenObtainPairView.as_view(), name='login'),
    path('logout/', TokenBlacklistView.as_view(), name='token_blacklist'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('add-permissions/', AddPermissionsAPIView.as_view(), name='add_permissions'), 
    path('users/', UsersAPIView.as_view(), name='manage_users'),

    path('etudiants/', EtudiantsAPIView.as_view(), name='manage_etudiants'),
    path('professeurs/', ProfesseursAPIView.as_view(), name='manage_professeurs'),
    path('departments/', DepartmentView.as_view(), name='manage_department'),
    path('departments/<uuid:pk>/', DepartmentView.as_view(), name='manage_department_id'),
    path('courses/', CourseView.as_view(), name='manage_course'),
    path('courses/<uuid:pk>/', CourseView.as_view(), name='manage_course_id'),
    path('content_courses/<uuid:course_id>/', ContentCourseView.as_view(), name='create_content_course'),
    path('content_courses_detail/<uuid:pk>/', ContentCourseView.as_view(), name='get_content_course'),
    path('enrollments/', EnrollmentView.as_view(), name='manage_enrollment'),
    path('student_results/', ResultView.as_view(), name='manage_student_result'),
    path('student_results/<uuid:pk>/', ResultView.as_view(), name='manage_student_result_by_id'),
    path('evaluations/', EvaluationView.as_view(), name='manage_evaluations'),
    path('evaluations/<uuid:pk>/', EvaluationView.as_view(), name='manage_evaluations_by_id'),
    path('evaluations_create/<uuid:course_id>/', EvaluationView.as_view(), name='create_evaluations_by_course'),
    path('questions/', QuestionsView.as_view(), name='manage_questions'),
    path('questions_create/<uuid:course_id>/', QuestionsView.as_view(), name='create_questions_by_id'),
    path('questions/<uuid:pk>/', QuestionsView.as_view(), name='manage_questions_by_id'),
    path('specialities/', SpecialityView.as_view(), name='manage_speciality'),
    path('specialities/<uuid:pk>/', SpecialityView.as_view(), name='manage_speciality_by_id'),
    path('activity_repports/', ActivityRepportView.as_view(), name='manage_activity_repports'),
]
