# Generated by Django 5.0.7 on 2024-07-26 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('employee_updater', models.CharField(blank=True, max_length=255, null=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('employee_updater', models.CharField(blank=True, max_length=255, null=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('chef_de_departement', models.ForeignKey(limit_choices_to={'status': 'professeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('employee_updater', models.CharField(blank=True, max_length=255, null=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='departements.cours')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('employee_updater', models.CharField(blank=True, max_length=255, null=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialites', to='departements.departement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='departements.specialite'),
        ),
    ]
