# Generated by Django 5.0.7 on 2024-07-26 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='chef_de_departement',
            field=models.ForeignKey(limit_choices_to={'status': 'Professeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements', to=settings.AUTH_USER_MODEL),
        ),
    ]
