# Generated by Django 5.0.7 on 2024-07-26 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0002_alter_departement_chef_de_departement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='nom_professeur',
            field=models.ForeignKey(limit_choices_to={'status': 'Professeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_professeur', to=settings.AUTH_USER_MODEL),
        ),
    ]
