# Generated by Django 5.0.4 on 2025-04-18 17:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0003_cours_nom_professeur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='departement',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='lecon',
            options={'ordering': ['titre']},
        ),
        migrations.AlterModelOptions(
            name='specialite',
            options={'ordering': ['nom']},
        ),
        migrations.RenameField(
            model_name='cours',
            old_name='time_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cours',
            old_name='employee_updater',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='cours',
            old_name='time_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='departement',
            old_name='time_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='departement',
            old_name='employee_updater',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='departement',
            old_name='time_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='lecon',
            old_name='time_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='lecon',
            old_name='employee_updater',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='lecon',
            old_name='time_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='specialite',
            old_name='time_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='specialite',
            old_name='employee_updater',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='specialite',
            old_name='time_updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='cours',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cours',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lecon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lecon',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specialite',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='specialite',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cours',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cours',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_specialite', to='departements.specialite'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='chef_de_departement',
            field=models.ForeignKey(limit_choices_to={'status': 'Professeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='departement',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
