# Generated by Django 5.0.7 on 2024-07-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enspd_webapp_api_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='status',
            field=models.CharField(choices=[('E', 'Etudiant'), ('P', 'Professeur')], max_length=1),
        ),
    ]
