# Generated by Django 5.0.7 on 2024-07-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enspd_webapp_api_auth', '0002_alter_usermember_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='status',
            field=models.CharField(choices=[('Etudiant', 'Etudiant'), ('Professeur', 'Professeur'), ('Admin', 'Admin')], max_length=10),
        ),
    ]
