# Generated by Django 5.0.7 on 2024-07-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enspd_webapp_api_auth', '0004_alter_usermember_groups_alter_usermember_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='sexe',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], default='Masculin', max_length=10),
        ),
    ]
