# Generated by Django 5.0.7 on 2024-07-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enspd_webapp_api_auth', '0005_usermember_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='sexe',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], default='e', max_length=10),
        ),
    ]
