# Generated by Django 5.0.4 on 2025-04-23 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enspd_webapp_api_auth', '0009_activityreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='speciality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='enspd_webapp_api_auth.speciality'),
            preserve_default=False,
        ),
    ]
