# Generated by Django 5.0.4 on 2025-04-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enspd_webapp_api_auth', '0010_remove_course_department_course_speciality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='name',
        ),
    ]
