# Generated by Django 5.0.4 on 2025-04-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enspd_webapp_api_auth', '0011_rename_title_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content',
            field=models.CharField(blank=True, max_length=2024, null=True),
        ),
    ]
